obj-$(CONFIG_PINCTRL_RTD119X)	+= pinctrl-rtd119x.o
obj-$(CONFIG_PINCTRL_RTD129x)	+= pinctrl-rtd129x.o
obj-$(CONFIG_PINCTRL_RTD139x)	+= pinctrl-rtd139x.o
obj-$(CONFIG_PINCTRL_RTD16xx)	+= pinctrl-rtd16xx.o
