dtb-$(CONFIG_ARCH_RTD16xx) += rtd-1619-mjolnir-2GB.dtb
dtb-$(CONFIG_ARCH_RTD16xx) += rtd-1619-qa-rescue.dtb
dtb-$(CONFIG_ARCH_RTD16xx) += thor-fpga.dtb
dtb-$(CONFIG_ARCH_RTD16xx) += rtd-1619-mjolnir-nand-2GB.dtb


always          := $(dtb-y)
subdir-y        := $(dts-dirs)
clean-files     := *.dtb

