#ifndef __DT_BINDINGS_REGULATOR_ANPEC_APW888X_H
#define __DT_BINDINGS_REGULATOR_ANPEC_APW888X_H

#define APW8889_DC_MODE_AUTO              (0x0)
#define APW8889_DC_MODE_FORCE_PWM         (0x1)
#define APW8889_LDO_MODE_NORMAL           (APW8889_DC_MODE_AUTO)

#define APW888X_DC_MODE_AUTO              (0x0)
#define APW888X_DC_MODE_FORCE_PWM         (0x1)
#define APW888X_LDO_MODE_NORMAL           (APW888X_DC_MODE_AUTO)

#endif
