obj-$(CONFIG_ARCH_RTD119X)		+= rtd119x_restart.o
obj-$(CONFIG_HOTPLUG_CPU)		+= rtd119x_hotplug.o
obj-$(CONFIG_ARCH_RTD119X)		+= rtk_chip.o
obj-$(CONFIG_SUSPEND)			+= rtd119x_suspend.o rtd119x_resume.o rtd119x_ip_power.o

obj-$(CONFIG_SCPU_SRAMCTL_RTD119X)      += rtd119x_scpu_sramctl.o
