dtb-$(CONFIG_ARCH_RTD119X) += \
        rtd-119x-horseradish.dtb \
        rtd-119x-horseradish-tee.dtb \
        rtd-119x-qa-rescue.dtb \
	rtd-119x-horseradish-nand.dtb \
	rtd-119x-qa-rescue-nand.dtb


always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
