obj-$(CONFIG_ARCH_RTD129x) += rtd129x_spin_table.o rtd129x_cpu_hotplug.o rtd129x_cpu_wrapper.o rtd129x_restart.o
obj-$(CONFIG_ARCH_RTD129x) += rtk_chip.o
obj-$(CONFIG_ARCH_RTD129x) += rtk_usb.o
obj-$(CONFIG_SUSPEND) += rtd129x_suspend.o
obj-$(CONFIG_RTK_SW_LOCK_API) += rtd129x_lockapi.o
obj-$(CONFIG_RTK_FAN) += rtd129x_fan.o
obj-$(CONFIG_RTK_ACPU_RELOAD) += avcpu.o

obj-$(CONFIG_RTK_CWMP_TREE) += cwmp/
obj-$(CONFIG_RTK_CODEC) += rtk_ve/
