#include <soc/realtek/kernel-rpc.h>

#include "uapi/ion.h"
#include "ion/ion.h"
#include "uapi/ion_rtk.h"


/* From FW amw_kernel_rpc.h */
typedef enum {
	ENUM_KERNEL_RPC_CREATE_AGENT,
	ENUM_KERNEL_RPC_INIT_RINGBUF,
	ENUM_KERNEL_RPC_PRIVATEINFO,
	ENUM_KERNEL_RPC_RUN,
	ENUM_KERNEL_RPC_PAUSE,
	ENUM_KERNEL_RPC_SWITCH_FOCUS,
	ENUM_KERNEL_RPC_MALLOC_ADDR,
	ENUM_KERNEL_RPC_VOLUME_CONTROL,
	ENUM_KERNEL_RPC_FLUSH,
	ENUM_KERNEL_RPC_CONNECT,
	ENUM_KERNEL_RPC_SETREFCLOCK,
	ENUM_KERNEL_RPC_DAC_I2S_CONFIG,
	ENUM_KERNEL_RPC_DAC_SPDIF_CONFIG,
	ENUM_KERNEL_RPC_HDMI_OUT_EDID,
	ENUM_KERNEL_RPC_HDMI_OUT_EDID2,
	ENUM_KERNEL_RPC_HDMI_SET,
	ENUM_KERNEL_RPC_HDMI_MUTE,
	ENUM_KERNEL_RPC_ASK_DBG_MEM_ADDR,
	ENUM_KERNEL_RPC_DESTROY,
	ENUM_KERNEL_RPC_STOP,
	ENUM_KERNEL_RPC_CHECK_READY,   // check if Audio get memory pool from AP
	ENUM_KERNEL_RPC_GET_MUTE_N_VOLUME,	 // get mute and volume level
	ENUM_KERNEL_RPC_EOS,
	ENUM_KERNEL_RPC_ADC0_CONFIG,
	ENUM_KERNEL_RPC_ADC1_CONFIG,
	ENUM_KERNEL_RPC_ADC2_CONFIG,
#if defined(AUDIO_TV_PLATFORM)
	ENUM_KERNEL_RPC_BBADC_CONFIG,
	ENUM_KERNEL_RPC_I2SI_CONFIG,
	ENUM_KERNEL_RPC_SPDIFI_CONFIG,
#endif // AUDIO_TV_PLATFORM
	ENUM_KERNEL_RPC_HDMI_OUT_VSDB,
	ENUM_VIDEO_KERNEL_RPC_CONFIG_TV_SYSTEM,
	ENUM_VIDEO_KERNEL_RPC_CONFIG_HDMI_INFO_FRAME,
	ENUM_VIDEO_KERNEL_RPC_QUERY_DISPLAY_WIN,
	ENUM_VIDEO_KERNEL_RPC_PP_INIT_PIN,
	ENUM_KERNEL_RPC_INIT_RINGBUF_AO,
	ENUM_VIDEO_KERNEL_RPC_VOUT_EDID_DATA,
	ENUM_KERNEL_RPC_AUDIO_POWER_SET,
	ENUM_VIDEO_KERNEL_RPC_VOUT_VDAC_SET,
	ENUM_VIDEO_KERNEL_RPC_QUERY_CONFIG_TV_SYSTEM
} ENUM_AUDIO_KERNEL_RPC_CMD;


enum VIDEO_ENUM_PRIVATEINFO {
	ENUM_PRIVATEINFO_VIDEO_CHECK_SECURITY_ID = 0,
	ENUM_PRIVATEINFO_VIDEO_DISPLAY_RATIO = 1,
	ENUM_PRIVATEINFO_VIDEO_DISPLAY_X_Y_W_H = 2,
	ENUM_PRIVATEINFO_VIDEO_CVBS_POWER_OFF = 3,
	ENUM_PRIVATEINFO_VIDEO_VO_CAPTURE = 4,
	ENUM_PRIVATEINFO_VIDEO_VDAC_POWER_OFF = 5,
	ENUM_PRIVATEINFO_HDMI_RANGE_SETTING = 6,
	ENUM_PRIVATEINFO_VO_DISPLAY_RATIO_TYPE = 7,
	ENUM_PRIVATEINFO_MIXDD_DISPLAY_RATIO = 8,
	ENUM_PRIVATEINFO_MIX1_DISPLAY_RATIO = 9,
	ENUM_PRIVATEINFO_MIX2_DISPLAY_RATIO = 10,
};

struct VIDEO_RPC_PRIVATEINFO_PARAMETERS {
	unsigned int instanceID;
	enum VIDEO_ENUM_PRIVATEINFO type;
	unsigned int privateInfo[16];
};


