dts-dirs += rtd139x
dts-dirs += rtd119x
dts-dirs += rtd16xx
dts-dirs += rtd13xx

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= rtd119x/*.dtb rtd139x/*.dtb rtd16xx/*.dtb rtd13xx/*.dtb *.dtb

