ifndef CONFIG_ARCH_MULTI_V7
obj-$(CONFIG_ARCH_RTD139x) += rtd139x_spin_table.o rtd139x_cpu_hotplug.o rtd139x_cpu_wrapper.o rtd139x_restart.o
endif
obj-$(CONFIG_ARCH_RTD139x) += rtk_chip.o
obj-$(CONFIG_ARCH_RTD139x) += rtk_usb.o
obj-$(CONFIG_RTK_SW_LOCK_API) += rtd139x_lockapi.o
obj-$(CONFIG_RTK_ACPU_RELOAD) += avcpu.o
obj-$(CONFIG_SUSPEND) += rtd139x_suspend.o
obj-$(CONFIG_RTK_CODEC) += rtk_ve/
obj-$(CONFIG_ARCH_MULTI_V7) += aarch32/
