obj-$(CONFIG_RTK_SECURE_DVFS) += secure_dvfs.o
obj-$(CONFIG_RTK_CPU_CACHE_SUPPLY_COORDINATOR) += cpu-cache-supp-coord.o
obj-$(CONFIG_RTK_CPU_SUPPLY_ENHANCER) += cpu-supp-enh.o
obj-$(CONFIG_RTK_CPU_HIGH_LOAD_BOOSTER) += cpu-hlb.o
obj-$(CONFIG_RTK_CPU_VOLT_SEL) += cpu-volt-sel.o
