#ifndef __DT_BINDINGS_RTK_CLOCK_RTD129X_H
#define __DT_BINDINGS_RTK_CLOCK_RTD129X_H

/* 0x9800000C */
#define CLK_EN_MISC             0
#define CLK_EN_PCIE0            1
#define CLK_EN_SATA_0           2
#define CLK_EN_GSPI             3
#define CLK_EN_USB              4
#define CLK_EN_PCR              5
#define CLK_EN_ISO_MISC         6
#define CLK_EN_SATA_ALIVE_0     7
#define CLK_EN_HDMI             8
#define CLK_EN_ETN              9
#define CLK_EN_AIO             10
#define CLK_EN_GPU             11
#define CLK_EN_VE1             12
#define CLK_EN_VE2             13
#define CLK_EN_TVE             14
#define CLK_EN_VO              15
#define CLK_EN_LVDS            16
#define CLK_EN_SE              17
#define CLK_EN_DCU             18
#define CLK_EN_CP              19
#define CLK_EN_MD              20
#define CLK_EN_TP              21
#define CLK_EN_RSA             22
#define CLK_EN_NF              23
#define CLK_EN_EMMC            24
#define CLK_EN_CR              25
#define CLK_EN_SDIO_IP         26
#define CLK_EN_MIPI            27
#define CLK_EN_EMMC_IP         28
#define CLK_EN_VE3             29
#define CLK_EN_SDIO            30
#define CLK_EN_SD_IP           31

/* 0x98000010 */
#define CLK_EN_NAT              0
#define CLK_EN_MISC_I2C_5       1
#define CLK_EN_SCPU             2
#define CLK_EN_JPEG             3
#define CLK_EN_ACPU             4
#define CLK_EN_PCIE1            5
#define CLK_EN_MISC_SC          6
#define CLK_EN_CBUS_TX          7
#define CLK_EN_MISC_RTC        10
#define CLK_EN_MISC_I2C_4      13
#define CLK_EN_MISC_I2C_3      14
#define CLK_EN_MISC_I2C_2      15
#define CLK_EN_MISC_I2C_1      16
#define CLK_EN_AIO_AU_CODEC    17
#define CLK_EN_AIO_MOD         18
#define CLK_EN_AIO_DA          19
#define CLK_EN_AIO_HDMI        20
#define CLK_EN_AIO_SPDIF       21
#define CLK_EN_AIO_I2S         22
#define CLK_EN_AIO_MCLK        23
#define CLK_EN_HDMIRX          24
#define CLK_EN_SATA_1          25
#define CLK_EN_SATA_ALIVE_1    26
#define CLK_EN_UR2             27
#define CLK_EN_UR1             28
#define CLK_EN_FAN             29
#define CLK_EN_DCPHY_0         30
#define CLK_EN_DCPHY_1         31

/* 0x9800708C */
#define CLK_EN_MISC_MIX         0
#define CLK_EN_MISC_CEC0        2
#define CLK_EN_CBUSRX_SYS       3
#define CLK_EN_CBUSTX_SYS       4
#define CLK_EN_CBUS_SYS         5
#define CLK_EN_CBUS_OSC         6
#define CLK_EN_MISC_IR          7
#define CLK_EN_MISC_UR0         8
#define CLK_EN_I2C0             9
#define CLK_EN_I2C1            10
#define CLK_EN_ETN_250M        11
#define CLK_EN_ETN_SYS         12

/* CC */
#define CC_PLL_SCPU             0
#define CC_CLK_SCPU             1
#define CC_CLK_SCPU_SET         2
#define CC_PLL_BUS              3
#define CC_PLL_BUS_DIV2         4
#define CC_CLK_SYS              5
#define CC_CLK_SYS_SB2          6
#define CC_PLL_BUS_H            7
#define CC_CLK_SYSH             8
#define CC_PLL_DDSA             9
#define CC_PLL_DDSB            10
#define CC_PLL_GPU             11
#define CC_CLK_GPU             12
#define CC_PLL_VE1             13
#define CC_PLL_VE2             14
#define CC_CLK_VE1             15
#define CC_CLK_VE2             16
#define CC_CLK_VE3             17
#define CC_PLL_VODMA           18
#define CC_PLL_ACPU            19
#define CC_CLK_ACPU            20
#define CC_CLK_MAX             21

#endif
