obj-$(CONFIG_ARCH_RTD16xx) += rtd16xx_spin_table.o rtd16xx_cpu_hotplug.o rtd16xx_cpu_wrapper.o
obj-$(CONFIG_ARCH_RTD16xx) += rtk_chip.o
obj-$(CONFIG_ARCH_RTD16xx) += rtk_usb.o
obj-$(CONFIG_SUSPEND) += rtd16xx_suspend.o rtd16xx_suspend_fs.o rtd16xx_suspend_mem.o rtd16xx_psci.o
obj-$(CONFIG_RTK_CODEC) += rtk_ve/