#ifndef __DT_BINDINGS_RTK_RESET_RTD129X_H
#define __DT_BINDINGS_RTK_RESET_RTD129X_H

/* 0x98000000 */
#define RSTN_MISC               0
#define RSTN_NAT                1
#define RSTN_USB3_PHY0_POW      2
#define RSTN_GSPI               3
#define RSTN_USB3_P0_MDIO       4
#define RSTN_SATA_0             5
#define RSTN_USB                6
#define RSTN_SATA_PHY_0         7
#define RSTN_USB_PHY0           8
#define RSTN_USB_PHY1           9
#define RSTN_SATA_PHY_POW_0    10
#define SATA_FUNC_EXIST_0      11
#define RSTN_HDMI              12
#define RSTN_VE1               13
#define RSTN_VE2               14
#define RSTN_VE3               15
#define RSTN_ETN               16
#define RSTN_AIO               17
#define RSTN_GPU               18
#define RSTN_TVE               19
#define RSTN_VO                20
#define RSTN_LVDS              21
#define RSTN_SE                22
#define RSTN_DCU               23
#define RSTN_DC_PHY            24
#define RSTN_CP                25
#define RSTN_MD                26
#define RSTN_TP                27
#define RSTN_AE                28
#define RSTN_NF                29
#define RSTN_MIPI              30
#define RSTN_RSA               31

/* 0x98000004 */
#define RSTN_ACPU               0
#define RSTN_JPEG               1
#define RSTN_USB_PHY3           2
#define RSTN_USB_PHY2           3
#define RSTN_USB3_PHY1_POW      4
#define RSTN_USB3_P1_MDIO       5
#define RSTN_PCIE0_STITCH       6
#define RSTN_PCIE0_PHY          7
#define RSTN_PCIE0              8
#define RSTN_PCR_CNT            9
#define RSTN_CR                10
#define RSTN_EMMC              11
#define RSTN_SDIO              12
#define RSTN_PCIE0_CORE        13
#define RSTN_PCIE0_POWER       14
#define RSTN_PCIE0_NONSTITCH   15
#define RSTN_PCIE1_PHY         16
#define RSTN_PCIE1             17
#define RSTN_I2C_5             18
#define RSTN_PCIE1_STITCH      19
#define RSTN_PCIE1_CORE        20
#define RSTN_PCIE1_POWER       21
#define RSTN_PCIE1_NONSTITCH   22
#define RSTN_I2C_4             23
#define RSTN_I2C_3             24
#define RSTN_I2C_2             25
#define RSTN_I2C_1             26
#define RSTN_UR2               27
#define RSTN_UR1               28
#define RSTN_MISC_SC           29
#define RSTN_CBUS_TX           30
#define RSTN_SDS_PHY           31

/* 0x98000008 */
#define RSTN_SB2                0

/* 0x98000050 */
#define RSTN_DCPHY_CRT          0
#define RSTN_DCPHY_ALERT_RX     1
#define RSTN_DCPHY_PTR          2
#define RSTN_DCPHY_LDO          3
#define RSTN_DCPHY_SSC_DIG      4
#define RSTN_HDMIRX             5
#define RSTN_CBUSRX             6
#define RSTN_SATA_PHY_POW_1     7
#define SATA_FUNC_EXIST_1       8
#define RSTN_SATA_PHY_1         9
#define RSTN_SATA_1            10
#define RSTN_FAN               11
#define RSTN_HDMIRX_WRAP       12
#define RSTN_PCIE0_PHY_MDIO    13
#define RSTN_PCIE1_PHY_MDIO    14
#define RSTN_DISP              15

/* 0x98007084 */
#define IRSTN_IR                1
#define IRSTN_CEC0              2
#define IRSTN_CEC1              3
#define IRSTN_DP                4
#define IRSTN_CBUSTX            5
#define IRSTN_CBUSRX            6
#define IRSTN_EFUSE             7
#define IRSTN_UR0               8
#define IRSTN_GMAC              9
#define IRSTN_GPHY             10
#define IRSTN_I2C_0            11
#define IRSTN_I2C_1            12
#define IRSTN_CBUS             13

#endif
