obj-$(CONFIG_ARCH_RTD119X)      += rtd119x/ common/
obj-$(CONFIG_ARCH_RTD129x)	+= rtd129x/ common/
obj-$(CONFIG_ARCH_RTD139x)	+= rtd139x/ common/
obj-$(CONFIG_ARCH_RTD16xx)      += rtd16xx/ common/
obj-$(CONFIG_RTK_XEN_SUPPORT)   += xen/
