dtb-$(CONFIG_ARCH_RTD139x) += hercules-fpga.dtb
dtb-$(CONFIG_ARCH_RTD139x) += rtd-1395-lionskin-384MB.CMAx2.dtb
dtb-$(CONFIG_ARCH_RTD139x) += rtd-1395-lionskin-512MB.CMAx2.dtb
dtb-$(CONFIG_ARCH_RTD139x) += rtd-1395-lionskin-1GB.dtb
dtb-$(CONFIG_ARCH_RTD139x) += rtd-1395-lionskin-1GB.atv.dtb
dtb-$(CONFIG_ARCH_RTD139x) += rtd-1395-lionskin-1GB.atv-avb.dtb
dtb-$(CONFIG_ARCH_RTD139x) += rtd-1395-lionskin-1GB.atv-tee.dtb
dtb-$(CONFIG_ARCH_RTD139x) += rtd-1395-lionskin-1GB.CMAx2.dtb
dtb-$(CONFIG_ARCH_RTD139x) += rtd-1395-lionskin-1GB.CMAx2.MEMTEST.dtb
dtb-$(CONFIG_ARCH_RTD139x) += rtd-1395-lionskin-2GB.dtb
dtb-$(CONFIG_ARCH_RTD139x) += rtd-1395-lionskin-2GB-avb.dtb
dtb-$(CONFIG_ARCH_RTD139x) += rtd-1395-lionskin-2GB.MEMTEST.dtb
dtb-$(CONFIG_ARCH_RTD139x) += rtd-1355-gnarledclub-1GB.dtb
dtb-$(CONFIG_ARCH_RTD139x) += rtd-1355-gnarledclub-1GB.atv.dtb
dtb-$(CONFIG_ARCH_RTD139x) += rtd-1355-gnarledclub-1GB.atv-tee.dtb
dtb-$(CONFIG_ARCH_RTD139x) += rtd-1355-gnarledclub-1GB.CMAx2.dtb
dtb-$(CONFIG_ARCH_RTD139x) += rtd-1355-gnarledclub-1GB.CMAx2.MEMTEST.dtb
dtb-$(CONFIG_ARCH_RTD139x) += rtd-1355-gnarledclub-2GB.dtb
dtb-$(CONFIG_ARCH_RTD139x) += rtd-1355-gnarledclub-2GB.MEMTEST.dtb
dtb-$(CONFIG_ARCH_RTD139x) += rtd-1395-arete-1GB.dtb
dtb-$(CONFIG_ARCH_RTD139x) += rtd-1395-arete-1GB.atv.dtb
dtb-$(CONFIG_ARCH_RTD139x) += rtd-1395-arete-1GB.atv-tee.dtb
dtb-$(CONFIG_ARCH_RTD139x) += rtd-1395-arete-1GB.CMAx2.dtb
dtb-$(CONFIG_ARCH_RTD139x) += rtd-1395-arete-768MB.CMAx2.dtb
dtb-$(CONFIG_ARCH_RTD139x) += rtd-1395-arete-512MB.CMAx2.dtb
dtb-$(CONFIG_ARCH_RTD139x) += rtd-1395-arete-384MB.CMAx2.dtb
dtb-$(CONFIG_ARCH_RTD139x) += rtd-1395-arete-384MB.dtb
dtb-$(CONFIG_ARCH_RTD139x) += rtd-1395-arete-rescue.dtb
dtb-$(CONFIG_ARCH_RTD139x) += rtd-1395-qa-rescue.dtb
dtb-$(CONFIG_ARCH_RTD139x) += rtd-1355-qa-rescue.dtb
dtb-$(CONFIG_ARCH_RTD139x) += rtd-1395-qa-rescue-nand.dtb
dtb-$(CONFIG_ARCH_RTD139x) += rtd-1395-lionskin-nand-1GB.dtb
dtb-$(CONFIG_ARCH_RTD139x) += rtd-1395-lionskin-nand-1GB.CMAx2.dtb
dtb-$(CONFIG_ARCH_RTD139x) += rtd-1395-lionskin-nand-2GB.dtb
dtb-$(CONFIG_ARCH_RTD139x) += rtd-1395-papermulberry-1GB.dtb
dtb-$(CONFIG_ARCH_RTD139x) += rtd-1395-papermulberry-qa-rescue.dtb

dtb-$(CONFIG_ARCH_RTD139x) += rtd-1395-lionskin-2GB-ab.dtb
dtb-$(CONFIG_ARCH_RTD139x) += rtd-1395-lionskin-2GB-verity.dtb

dtb-$(CONFIG_ARCH_RTD139x) += rtd-1395-lionskin-2GB-tee.dtb
dtb-$(CONFIG_ARCH_RTD139x) += rtd-1395-lionskin-2GB-tee-vmx.dtb
dtb-$(CONFIG_ARCH_RTD139x) += rtd-1395-qa-rescue-tee.dtb

dtb-$(CONFIG_ARCH_RTD139x) += rtd-1395-qa-rescue-vmx.dtb

dtb-$(CONFIG_ARCH_RTD139x) += rtd-1395-lionskin-glinux-1GB.dtb
dtb-$(CONFIG_ARCH_RTD139x) += rtd-1395-lionskin-glinux-2GB.dtb
dtb-$(CONFIG_ARCH_RTD139x) += rtd-1355-gnarledclub-glinux-1GB.dtb
dtb-$(CONFIG_ARCH_RTD139x) += rtd-1355-gnarledclub-glinux-2GB.dtb
dtb-$(CONFIG_ARCH_RTD139x) += rtd-1395-lionskin-nand-glinux-1GB.dtb
dtb-$(CONFIG_ARCH_RTD139x) += rtd-1395-lionskin-nand-glinux-2GB.dtb
dtb-$(CONFIG_ARCH_RTD139x) += rtd-1395-papermulberry-glinux-1GB.dtb
dtb-$(CONFIG_ARCH_RTD139x) += rtd-1395-lionskin-glinux-2GB-tee.dtb

dtb-$(CONFIG_ARCH_RTD139x) += rtd-1395-lionskin-1GB-xendom0.dtb
dtb-$(CONFIG_ARCH_RTD139x) += rtd-1395-lionskin-2GB-xendom0.dtb
dtb-$(CONFIG_ARCH_RTD139x) += rtd-1395-lionskin-xenott.dtb
dtb-$(CONFIG_ARCH_RTD139x) += rtd-1395-lionskin-xenott.low.dtb
dtb-$(CONFIG_ARCH_RTD139x) += rtd-1395-lionskin-xenott.CMAx2.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
