ifndef CONFIG_CPU_V7
obj-$(CONFIG_ARCH_RTD13xx) += rtd13xx_spin_table.o rtd13xx_cpu_hotplug.o rtd13xx_cpu_wrapper.o
endif

obj-$(CONFIG_ARCH_RTD13xx) += rtk_chip.o
obj-$(CONFIG_ARCH_RTD13xx) += rtk_usb.o
obj-$(CONFIG_ARM_PSCI_FW) += rtd13xx_psci.o
obj-$(CONFIG_SUSPEND) += rtd13xx_suspend.o rtd13xx_suspend_fs.o rtd13xx_suspend_mem.o
obj-$(CONFIG_RTK_CODEC) += rtk_ve/
obj-$(CONFIG_CPU_V7) += aarch32/