dts-dirs += rtd129x
dts-dirs += rtd139x
dts-dirs += rtd16xx

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= rtd129x/*.dtb *.dtb
clean-files	:= rtd139x/*.dtb *.dtb
clean-files	:= rtd16xx/*.dtb *.dtb
